on: workflow_dispatch
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: kong/setup-inso@v1
        with:
          inso-version: 8.4.2
          compression: gzip
      - run: inso --version
